### PR TITLE
testing redis action

### PR DESCRIPTION
**Pull request by vishnudxb**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by boesing** [comment]
Hey @vishnudxb,

thanks for the quick feedback. I did not expect this to be answered that fast. Awesome!

Yes, you are right, there are jobs still passing because they do not interact with the redis-cluster. Only the unit tests and benchmarks are interacting with the cluster and therefore, we somehow need to access the cluster from within our CI container.

That leads me to the question:

How can I connect from one GHA to another GHA? 
As the action configured in your PR only forwards the ports to the host and thus is not automatically accessible from within another action. Or at least I am not aware of how to interact with the cluster from another action.

**Comment by vishnudxb** [comment]
@boesing  Do we need the cluster to accessible from another GHA? Currently each job have its own cluster and I noticed it can aconnect as well in the failed actions.
Screenshot 2022-12-07 at 10 06 44 AM

May I know which address your unit test is trying to access ?

Screenshot 2022-12-07 at 10 08 13 AM

**Comment by vishnudxb** [comment]
@boesing  Looks like it is not picking the env values? 
Screenshot 2022-12-07 at 10 30 32 AM
Screenshot 2022-12-07 at 10 30 12 AM

Also why you need a redis cluster and another redis instance? 

Screenshot 2022-12-07 at 10 29 46 AM

**Comment by vishnudxb** [comment]
Screenshot 2022-12-07 at 10 33 10 AM

**Comment by vishnudxb** [comment]
Screenshot 2022-12-07 at 10 39 48 AM

This is picking a cluster name which we dont have

**Comment by vishnudxb** [comment]
Screenshot 2022-12-07 at 10 40 24 AM

Here you can see it connects to the cluster. So it has something to do with how you connect the redis instance and run the unit test

**Comment by boesing** [comment]
No you are right, its not picking up the env values as these are only used in local environment.
So the problem is, that `127.0.0.1` won't work as a connection target because each "step" within our action is executed in a dedicated container:
https://github.com/laminas/laminas-cache-storage-adapter-redis/pull/59/files#diff-c471496bcb3ed47397b73d2e3e3aa41a8a679c86accaed9e05676fd9d5987434R31
https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/6493539006befb8ab16cd3f14dca90b6ea017e5b/.github/workflows/continuous-integration.yml#L40

Now that container needs to be able to connect to your container:
https://github.com/laminas/laminas-cache-storage-adapter-redis/pull/59/files#diff-c471496bcb3ed47397b73d2e3e3aa41a8a679c86accaed9e05676fd9d5987434R31

Since these containers are isolated from each other and do not run commands on the host, connecting to `127.0.0.1` will only result in a connection to the same container.

Your "Running Tests" works, because you are executing commands on the docker host which has access to the forwarded ports of your container.

---

So actually, our CI step needs to interact with your CI step somehow. They usually share the same network but I actually have no idea what the hostname of your container is and thus its impossible to provide proper configuration.

The hostname of your container needs to be configured in here:

https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/6493539006befb8ab16cd3f14dca90b6ea017e5b/.laminas-ci.json#L6

The other environment variables should not be modified as the `REDIS_HOST` needs to stay the name of the `service` (as we do create a redis instance there and that actually works as expected).

**Comment by boesing** [comment]
I already applied your changes to https://github.com/laminas/laminas-cache-storage-adapter-redis/pull/56 and configured some stuff to see if its working.

Have to go now, maybe it works with the last `tryfix` commit. If not, I still have to find out how to communicate with the redis-cluster of your action 😅

**Comment by boesing** [comment]
Just as a sidenode to avoid some trouble: 

please reset those changes unrelated to cluster such as redis port and redis host as these changes break tests which worked before. So we are unable to see if your changes are actually fixing cluster as non-cluster fails now as well.

and the second is: redis-cluster hostname needs to be part of the php.ini *or* I have to change the way the unit tests are connecting to the cluster.

However, I will see if I can apply your changes to my branch and modify the appropriate lines of code in the unit tests to see if we can connect to the cluster by using only one hostname (which is unusual for real applications tho). 

I guess that applying some changes to the cluster container (not the action) so that it does not interact with itself internally but externally would provide a more convenient fix than having to execute commands on the host to pass them to other actions.

I will see if I somehow get something to work, but your effort is really appreciated. If there is any way on how I can thank you more than just saying it, please let me know.

**Comment by vishnudxb** [comment]
@boesing I closed my PR. I tested the action to check if its working inside the gha with its own ipaddress and it is working. So now you need to update your action to pickup the gha ipaddress and hostname
Screenshot 2022-12-07 at 1 01 52 PM
Screenshot 2022-12-07 at 1 02 05 PM

**Comment by boesing** [comment]
Thanks for your help ☺️

**Pull request closed without merging**
