### PR TITLE
Use PSR ContainerInterface instead of Interop

### LINKED ISSUE #24: Usage of Interop\Container\ContainerInterface in AdapterPluginManagerDelegatorFactory precludes the use of PSR containers
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes

#### Summary

By using `Interop\Container\ContainerInterface` (which merely extends the PSR11 ContainerInterface) the usage of PSR11 containers such as `elie29/zend-di-config` is not possible. 

If the AdapterPluginManagerDelegatorFactory class were to use \Psr\Container\Container interface it would work for all implementations.

### PR DESCRIPTION
**Pull request by cooperaj**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description

When using a PSR11 Container such as `elie29/zend-di-config` it is not possible to use the included delegator factory as it is hardcoded to use the `Interop\Container\ContainerInterface`, even though that interface has extended `Psr\Container\ContainerInterface` for some time now.

This PR swaps out for the `Psr` version thus allowing PSR11 containers to be configured.

Fixes #24

### CODE REVIEW

**Comment by boesing** [comment]
Note to myself: since the class was final and container-interop implements the psr interface, we do still accept interop interfaces and thus this should not be a BC break. 
Have to double check this when I have some more time, but afaik we do conflict in laminas-cache with container-interop <1.2

Sorry that it takes that long @cooperaj

**Comment by cooperaj** [comment]
No worries. I'll be honest, I was confused about the BC break but I wasn't going to argue with the maintainer ;)

**Comment by boesing** [comment]
### To summarize

This is no BC break due to the fact, that `laminas/laminas-cache` since v3 requires [`laminas/laminas-servicemanager` in v3.7.0+](https://github.com/laminas/laminas-cache/blob/86b47eb7b05bc4d24edafb3039494ba81405983b/composer.json#L34).
`laminas/laminas-servicemanager` in v3.7.0+ requires [`container-interop/container-interop` v1.2.0+](https://github.com/laminas/laminas-servicemanager/blob/2b0aee477fdbd3191af7c302b93dbc5fda0626f4/composer.json#L28).
`container-interop/container-interop` in v1.2.0+ [implements `psr/container`](https://github.com/container-interop/container-interop/blob/79cbf1341c22ec75643d841642dd5d6acd83bdb8/src/Interop/Container/ContainerInterface.php#L13) and thus, we do still accept the injection of `container-interop` container instances.

**Comment by boesing** [comment]
Thanks, @cooperaj!

**Pull request merged**
